### ISSUE TITLE
library is distributed in raw JS State and generates error

### ISSUE THREAD

**Issue by mschipperheyn** [kkemple/graphql-auth#13]
This library is distrbuted in uncompiled state and generates the following error when used:
```
node_modules/graphql-auth/index.js:1
(function (exports, require, module, __filename, __dirname) { export class ContextError extends Error {
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)

```

Presumably this can be resolved by implementing
```
[`@babel/preset-env`, {
    modules: true,
    node: 'current'
}]
```

But it's generally not recommended to distribute libraries this way.

**Comment by kkemple** [comment]
It should have been compiled. It's fixed now!

**Comment by kkemple** [comment]
@mschipperheyn 	can you confirm it's working now?

**Comment by kkemple** [comment]
@mschipperheyn 	??

**Comment by mschipperheyn** [comment]
Thanks! I will have a go
