### ISSUE TITLE
Error: Cannot find module - fastify-gql

### ISSUE THREAD

**Issue by dougg0k** [kkemple/graphql-auth#21]
Hi,

I am trying out `graphql-auth` in a project, though I am getting the following error message after I implement `withAuth` in a resolver.
```
[ERROR] 12:26:15 Error: Cannot find module 'babel-runtime/core-js/promise'
Require stack:
- /app/node_modules/graphql-auth/build/index.js
...
```
I am using `fastify-gql` in a `typescript` project, I dont use Babel here.

Any idea on why this is happening?

Thanks!

**Comment by dougg0k** [comment]
I copied your code to my project and that solved the babel issue.

But another error happens regardless if I have `isAuthenticated` declared in the `context` or not, or if I have `scope[]` in the `withAuth` or not. It might just be compatibility issues.
```
ERROR (535 on 81ffff7483b5): Internal Server Error
    InternalServerError: Internal Server Error
        at Object.fastifyGraphQl [as graphql] (/app/node_modules/fastify-gql/index.js:384:19)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by dougg0k** [comment]
I actually built one myself for `fastify-gql`.

```
export const withAuth = (rolesAllowed: Array<string>, next: any) => (
	root: any,
	args: any,
	context: any,
	info: any,
) => {
	if (!context.isAuthenticated) {
		throw new Error("Unauthorized");
	}
	if (!rolesAllowed.includes(context.authorizedAs)) {
		throw new Error("Forbidden");
	}
	return next(root, args, context, info);
};
```
```
context: async (request: FastifyRequest) => {
	...
	return {
		isAuthenticated: isAuth,
		authorizedAs: role,
	};
}
```
```
Mutation: {
	createUser: withAuth(
		[ROLES.ADMIN],
		async (_parent: any, args: any) => {
			return await createUser(args);
		},
	),
},
```
